version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10 # Official CircleCI Python 3.10 image
    working_directory: ~/project

jobs:
  train:
    executor: python-executor
    
    # Hyperparameters to sweep via matrix
    parameters:
      learning_rate:
        type: string
      batch_size:
        type: string
      epochs:
        type: string
      lr_scheduler_type:
        type: string
    steps:
      - checkout

      - run:
          name: Set up Python
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Train with current hyperparameters
          command: |
            . venv/bin/activate
            python train.py \
              --learning_rate << parameters.learning_rate >> \
              --batch_size << parameters.batch_size >> \
              --epochs << parameters.epochs >> \
              --lr_scheduler_type << parameters.lr_scheduler_type >>

# Define workflow to run all matrix combinations
workflows:
  train-matrix:
    jobs:
      - train:
          # Set possible values of hyperparameters. Spawns differents jobs based on all combinations
          matrix: 
            parameters:
              learning_rate: ["1e-4", "1e-5"]
              batch_size: ["4", "8"]
              epochs: ["2", "4"]
              lr_scheduler_type: ["linear", "cosine"]